### ISSUE TITLE
新版本发布了！

### ISSUE THREAD

**Issue by MengChenJack** [WindyCloudCute/LANraragi_Chinese#2]
新的 LANraragi (v.0.9.0) 可用 !
求大佬GKD！

**Comment by FriendG1973** [comment]
同求，强迫症不能忍受更新提示（

**Comment by WindyCloudCute** [comment]
docker用户不是已经更新090了吗？🥵🥵

**Comment by FriendG1973** [comment]
<img width="1283" alt="image" src="https://github.com/WindyCloudCute/LANraragi_Chinese/assets/61214695/b7492921-f92e-4dc2-97a4-61bb5c7caee4">
2023.11.7 目前docker hub上看到的latest还是0.8.90🤣不知道是不是我操作有问题

**Comment by slqyxgrrad** [comment]
我也一样，汉化版应该还没更新吧

**Comment by WindyCloudCute** [comment]
应该是是Push失败了，得过两天我康康，这两天工作有点忙，不太能抽出时间来搞，抱歉了各位。😅

**Comment by LemonSoda-RPG** [comment]
> 应该是是Push失败了，得过两天我康康，这两天工作有点忙，不太能抽出时间来搞，抱歉了各位。😅

大佬能不能整个群进行交流  这里面的很多插件我都不知道怎么用😂

**Comment by LemonSoda-RPG** [comment]
> 应该是是Push失败了，得过两天我康康，这两天工作有点忙，不太能抽出时间来搞，抱歉了各位。😅

交流论坛打不开了

**Comment by WindyCloudCute** [comment]
> > 应该是是Push失败了，得过两天我康康，这两天工作有点忙，不太能抽出时间来搞，抱歉了各位。😅
> 
> 交流论坛打不开了

地址换了 我在主页改好了

**Comment by WindyCloudCute** [comment]
> > 应该是是Push失败了，得过两天我康康，这两天工作有点忙，不太能抽出时间来搞，抱歉了各位。😅
> 
> 大佬能不能整个群进行交流 这里面的很多插件我都不知道怎么用😂

有这个想法但是不知道用什么平台好一点 QQ吗

**Comment by WindyCloudCute** [comment]
很不幸的告诉各位,预计今晚发布的v0.9.0由于编译服务器这边的大佬在**整活**机子没了,估计还得晚点才能发布。😓

**Comment by LemonSoda-RPG** [comment]
> > > 应该是是Push失败了，得过两天我康康，这两天工作有点忙，不太能抽出时间来搞，抱歉了各位。😅
> > 
> > 
> > 大佬能不能整个群进行交流 这里面的很多插件我都不知道怎么用😂
> 
> 有这个想法但是不知道用什么平台好一点 QQ吗

qq或者tg都可以吧  但是qq更方便一些

**Comment by WindyCloudCute** [comment]
v.0.9.0 版本已经发布至Docker
