### ISSUE TITLE
在群晖7.2系统中，权限出现了错误

### ISSUE THREAD

**Issue by MengChenJack** [WindyCloudCute/LANraragi_Chinese#3]
如题，本人使用黑群晖DSM 7.2-64570 Update 3，使用Container Manager内置的docker-compose部署容器。当环境变量中设置LRR_UID=1026、LRR-GID=100时，会强制更改被映射进容器的共享文件夹的权限，使得该用户无法访问，如下图所示：
![QQ截图20231115212036](https://github.com/WindyCloudCute/LANraragi_Chinese/assets/88362579/7c82ddda-7cdf-4c54-b8b1-cfccfb60d0b4)
目前换用0.8.9版本，未出现此问题。

**Comment by WindyCloudCute** [comment]
映射进去的文件夹权限被改成了什么能看到吗?

**Comment by WindyCloudCute** [comment]
请把docker的设置截图一下 我都不知道你干了啥。

**Comment by MengChenJack** [comment]
> 请把docker的设置截图一下 我都不知道你干了啥。
您好，这是我的docker-compose设置：
![QQ图片20231116203608](https://github.com/WindyCloudCute/LANraragi_Chinese/assets/88362579/c806fc5c-6d5d-40ae-a51a-a21844b05441)
目前使用的镜像仍然是0.8.90版本。其中物理机的/volume1/comic文件夹为群晖创建的共享文件夹；/volume1/docker/lanraragi_cn是共享文件夹下的二级文件夹。

**Comment by WindyCloudCute** [comment]
我有个不懂的点,为啥要加个LRR_UID=1026、LRR-GID=100 默认的用户组不能访问吗?
这个项目本来就是为了群晖特化修改过的本就不应该LRR_UID=1026、LRR-GID=100 所以我得问清楚。

**Comment by MengChenJack** [comment]
> 我有个不懂的点,为啥要加个LRR_UID=1026、LRR-GID=100 默认的用户组不能访问吗? 这个项目本来就是为了群晖特化修改过的本就不应该LRR_UID=1026、LRR-GID=100 所以我得问清楚。

之前使用其他大佬的汉化版本时，需要添加这个变量否则进不去，我删除一下这个变量试试。因为在旧版本0.8.90使用这个环境变量没问题，所以没考虑到是这个环境变量的问题。

**Comment by MengChenJack** [comment]
> 我有个不懂的点,为啥要加个LRR_UID=1026、LRR-GID=100 默认的用户组不能访问吗? 这个项目本来就是为了群晖特化修改过的本就不应该LRR_UID=1026、LRR-GID=100 所以我得问清楚。

测试了一下不使用这两个环境变量，仍然出现了相同的问题。

**Comment by WindyCloudCute** [comment]
可以备份一下数据库切换到最新的`windycloud/lanraragi_cn:dev`试一下还有这个问题吗。
