### ISSUE TITLE
关于使用Filename Parsing插件

### ISSUE THREAD

**Issue by ycfeng666** [WindyCloudCute/LANraragi_Chinese#4]
如标题，在0.8.9版本后，使用这个插件对进行批量重命名与添加标签，完成之后再进入批量操作界面时，仍然把所有文档视为未添加标签

**Comment by WindyCloudCute** [comment]
这个得原作者修复,我没办法搞定.
我去看看他那边issues有没有提及,没有的话我测试看能不能复现然后给那边提交一下吧.
