### ISSUE TITLE
请问下完整汉化需要替换那些文件？

### ISSUE THREAD

**Issue by deadblue0910** [WindyCloudCute/LANraragi_Chinese#5]
windows版替换了templates和Plugin文件夹，还有少数的弹窗、UI未汉化，这些要替换哪些文件？
![2024-02-10_00-52-56](https://github.com/WindyCloudCute/LANraragi_Chinese/assets/48860218/b2a6c96b-51d6-4e70-ba7f-fbe29a035c43)
![2024-02-10_11-59-54](https://github.com/WindyCloudCute/LANraragi_Chinese/assets/48860218/04ce93f6-8c9f-47c1-b120-e59b5f8535d4)

**Comment by WindyCloudCute** [comment]
有些要自己写Js替换的 这会带来未知的问题 所以不是很推荐

**Comment by WindyCloudCute** [comment]
我没做过windws版的测试 这边依然推荐使用Docker或者Linux运行
